title: Blogs | Angad Sharma
baseURL: /
params:
  header:
    title: Angad Sharma
    has_nav: true
  footer:
    content: '&copy; All rights reserved.'
    has_social: true
  layout_style: grid
  palette: green
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
